### ISSUE TITLE
Header als Link

### ISSUE THREAD

**Issue by benCoder01** [Skn0tt/vplan-preact#2]
Wie wäre ein Header als Link zur Startseite?

**Comment by Skn0tt** [comment]
Ich mag mich täuschen, aber tut er das nicht bereits? 😄 
Müsste vielleicht UI-Mäßig klarer ersichtlich sein, hast du ne Idee wie man das ereichen könnte? Der typische Strich unterm link sieht immer so mies aus...

**Comment by benCoder01** [comment]
Hast recht, muss wohl nicht richtig geklickt haben.
