### ISSUE TITLE
Liste zur Auswahl der Kurse größer

### ISSUE THREAD

**Issue by benCoder01** [Skn0tt/vplan-preact#3]
Teilweise ist es so, dass beim Auswählen auf dem Handy die Liste zu klein ist und das wechseln auf andere Kurse nicht funktioniert.

**Comment by Skn0tt** [comment]
Ab welcher Displaygröße tritt das Problem auf? Dann kann ich das in den Chrome Dev-Tools einfacher nachstellen :smile:

**Comment by benCoder01** [comment]
Ich habe nen nexus5x. wie wäre es mit ner Auswahl, die über die ganzen Display geht... auch aus Designgründen.

**Comment by Skn0tt** [comment]
Ist nur Horizontal nicht genug Platz oder sind auch die ListItems nicht hoch genug?

**Comment by Skn0tt** [comment]
Ist mit 76fb0fecee374691d495bf2e16c7bd0fea1cdc9d gefixed.
Falls die Items auch Vertikal zu niedrig sind: Einfach wieder öffnen.
