### ISSUE TITLE
Bei der Unterstufe und Mittelstufe fehlen die Raumangaben

### ISSUE THREAD

**Issue by benCoder01** [Skn0tt/vplan-preact#6]
Soweit ich weiß, sollten auch bei den nicht Oberstüflern die Raumangaben u.a. bei Vertretungen vorhanden sein.

**Comment by Skn0tt** [comment]
Die Raumangaben gebe ich nur bei Arten an, wo es auch Sinn ergibt, sprich:
- Raumvertretung
- Klausur

Für alle anderen Arten macht mMn die Raumangabe keinen Sinn, siehst du das anders?
